In [ ]:
 #NumPy Panda

In [ ]:
import numpy as np
data=[1,2,3,4,5]
a1=np.array(data)
a1

array([1, 2, 3, 4, 5])

In [ ]:
import numpy as np
data1=[[1,2,3,4],[6,7,8,9]]
a2=np.array(data1)
a2

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
a1.ndim

1

In [ ]:
a2.ndim

2

In [ ]:
import numpy as np
array1=['aswathy','ps']
a3=np.array(array1)
a3

array(['aswathy', 'ps'], dtype='<U7')

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
#oD array
import numpy as np
array1=np.array(55)
print(array1)


55


In [ ]:
# 1D-Array
import numpy as np
array2=np.array([1,2,3,4,5])
print(array2)
print(array2.ndim)

[1 2 3 4 5]
1


In [ ]:
# 2D-Array
import numpy as np
array3=np.array([[1,2,3],[5,6,7]])
print(array3)
print(array3.ndim)

[[1 2 3]
 [5 6 7]]
2


In [ ]:
# 3D Array
import numpy as np
array4=([[[1,2,3],[4,5,6]],[[7,8,9],[5,3,1]]])
print(array4)
#print(array4.ndim)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [5, 3, 1]]]


In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
print(arr[1])

2


In [ ]:
print(arr[2]+arr[3])

7


In [ ]:
import numpy as np
arr1=np.array([[10,20,30,40],[50,60,70,80]])
print(arr1)
print("2nd element in 1st row",arr1[0,1])
print("2nd element in 2nd row",arr1[1,1])
print("last element from second row",arr1[1,-1])

[[10 20 30 40]
 [50 60 70 80]]
2nd element in 1st row 20
2nd element in 2nd row 60
last element from second row 80


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
# slicing
import numpy as np
arrs=np.array([10,20,30,40,50,60])
print(arrs[1:5])
print(arrs[:2])
print(arrs[2:])
print(arrs[-3:-1])

print(arrs[1:5:2])

[20 30 40 50]
[10 20]
[30 40 50 60]
[40 50]
[20 40]


In [ ]:
import numpy as np
arrays=np.array([1,2,3,4,5,6])
print(arrays[::2])
print(arrays[2::])
print(arrays[:5:])

[1 3 5]
[3 4 5 6]
[1 2 3 4 5]


In [ ]:
 # slicing 2D Array
import numpy as np
arrays1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arrays1)
print(arrays1[1,1:4])
print(arrays1[0:2,2]) #both element return index 2
print(arrays1.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]
int64
